apiVersion: v1
kind: Secret
metadata:
  name: req2veri-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "req2veri.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  jwt-secret-key: {{ .Values.secrets.jwtSecret | quote }}
  database-url: {{ printf "postgresql+psycopg2://req2veri:%s@postgres.%s.svc.cluster.local:5432/req2veri" .Values.secrets.postgresPassword .Release.Namespace | quote }}
